	CREATE DATABASE ACCOUNT;
    USE ACCOUNT;
    
    CREATE TABLE ACCOUNT(BALANCE DOUBLE, ACCOUNT_NUMBER INT PRIMARY KEY, TYPE VARCHAR(10), OWNER_CNIC INT, FOREIGN KEY(OWNER_CNIC) REFERENCES CUSTOMER(CNIC)); 
    CREATE TABLE CUSTOMER(NAME VARCHAR(255), ADRESS VARCHAR(255), PHONE_NO NUMERIC(11), CNIC INT PRIMARY KEY);
  